name: Metrics
on:
  # Schedule updates (ogni giorno a mezzanotte)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main", "master"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Mattia-Rollo
          template: classic
          
          # Manteniamo SOLO header e attivit√† di commit
          base: header, activity
          base_indepth: yes
          
          # Nascondiamo i dati "social" (follower, etc)
          config_display: large
          
          # Linguaggi
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          
          # Stile
          config_theme: tokyonight
